### ISSUE TITLE
[인게임 - 에픽 이슈] 인 게임 UI

### ISSUE THREAD

**Issue by 727207e** [kimdalho/ProjectT#12]
플레이어 체력바 활성화
몬스터들 상단에 작은 체력바 띄울것.

하단에 경험치 바 만들기.

**Comment by kimdalho** [comment]
# 인게임의 게임원근 설정은 아이소매트릭으로 하고싶다!!!

이유
1. 탑다운으로 인게임을 설정하면 하단의 경험치바 Ui로 다른 객체들의 시야를 가림
2. 세로방향의 게임 컨셉상 유저가 게임 플레시 하단 경험치 바는 유저의 손에 가려질 우려가 있다.
3. 이전 탑다운 게임 연출 표현 시 몰려오는 적 케릭터들의 모습이 제대로 표현되지못하는 아쉬움이 있었음

**Comment by 727207e** [comment]
ㅇㅋ 이슈 닫고 다시 파주셈

**Comment by kimdalho** [comment]
수정완료 제거
